# Generated by Django 4.2.3 on 2023-07-08 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('int', 'Blender Internal'), ('cyc', 'Cycles'), ('lux', 'Lux Render'), ('yfr', 'YafaRay'), ('oct', 'Octane'), ('nox', 'NOX Render')], max_length=3, verbose_name='render engine')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('draft', models.BooleanField(default=True, verbose_name='draft')),
                ('library', models.FileField(blank=True, upload_to=materials.models.get_filename, verbose_name='library')),
                ('preview', models.ImageField(blank=True, upload_to=materials.models.get_filename, verbose_name='preview')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
